# Site settings
title: LuncheryVN
email: luncheryvn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ghé thăm LuncheryVn.net và đặt ngay một bữa trưa ngon lành! Hệ thống book món ăn trên web tiên phong tại Việt Nam.
  Vận chuyển đúng giờ và chuyên nghiệp. Vào ngay LuncheryVn.Net và đăng ký để được giảm 50% xuất đặt hàng đầu tiên!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://luncheryvn.net" # the base hostname & protocol for your site
twitter_username: jekyllrb

# Build settings
markdown: kramdown
paginate: 5

authors:
  anhnguyen:
    name: Nguyen Quoc Anh
    display_name: Anh DH Nguyen
    image_url: "/assets/anhnguyen.jpg"
  nxqd:
    name: Nguyen Xuan Quang Dung
    display_name: Dung Nguyen
    image_url: "/assets/nxqd.jpg"

# Social
social_sharing:
  provider: like
  facebook:
    appid: 591309840991390
    layout: button_count
    faces: false
    width: 90
